### ISSUE TITLE
bl vs litepub

### ISSUE THREAD

**Issue by tyeeman** [mirovarga/bl#1]
Hello
   Just came to this repo to reread litepub manual and found you have now created this. Will bl be as easy to use as litepub. I really liked the one .exe with litepub but I'm not a coder so will Haskell be easy to execute on Windows? Like can I use bl now?

**Comment by mirovarga** [comment]
Hi,

Currently, `bl` is already usable, but you would need to build it yourself as there are no prebuilt binaries yet.

I hope that `bl` will be as easy to use as `litepub`, but there are a couple of differences between them, mainly:

- `bl` uses [Mustache](https://mustache.github.io/) for templating instead of [Go templates](https://golang.org/pkg/text/template/) (so the templates aren't tied to any particular language)
- `bl` needs a frontmatter at the start of each post (like in this [post](https://raw.githubusercontent.com/mirovarga/bl/main/blog/posts/from-litepub-to-bl-from-go-to-haskell.md)) instead of parsing things like title, date, ... from a post's Markdown

In addition to serving static files, `bl` also provides a readonly REST API for accessing posts.

I'm planning to write a thorough `README` in the near future so it is clearer how to use it.

**Comment by tyeeman** [comment]
Great,  I'll  wait for the binaries. Only thing that could be improved in Litepub was creating a page instead of a post. Currently I get around that with a not equal command looking at title names. If you could add this feature to bl that would be great. Probably in the meta area, add ispage or something like that so it would not be listed on the index page. I would link to it via a menu item.

**Comment by mirovarga** [comment]
I've been thinking about adding support for standalone pages that would have to be linked to manually - exactly as you're suggesting - so I've created an [issue](https://github.com/mirovarga/bl/issues/2) for it :)

**Comment by mirovarga** [comment]
I've just created a [release](https://github.com/mirovarga/bl/releases/tag/0.1.0) with prebuilt binaries for Linux and Windows.

**Comment by tyeeman** [comment]
Thanks for the binaries!

**Comment by mirovarga** [comment]
@tyeeman You're welcome.

BTW, I just released a new version with standalone posts: just add `standalone: yes` to a post's front matter to exclude it from the index and tag pages. For details see the README.
